### ISSUE TITLE
About the metrics AUC

### ISSUE THREAD

**Issue by TqXue** [bupt-ai-cz/HSA-NRL#6]
I just use the method sklearn.metrics.roc_auc_score to calculate AUC, but i don't know the parameter 'multi_class' should be 'ovo' or 'ovr'?? Then i find the result is close to your paper when use 'ovr', but worse when use 'ovo'. It's my appreciate if you could tell me which one i should choose.

**Comment by buptcwk** [comment]
You should choose "ovr".

**Comment by you-see-see** [comment]
> 

Thanks so much!
