### ISSUE TITLE
The result of using DM method on Chaoyang dataset is poor, but the results of using NF-Net on chaoyang is much higher!

### ISSUE THREAD

**Issue by TqXue** [bupt-ai-cz/HSA-NRL#8]
When I use the DM and NF-Net methods to reproduce on the Chaoyang dataset, 
the former's results(acc = 39.50) are very poor but the latter's results are much higher(acc = 75.06) than the results in your paper.
I am confused about this. Could you give me some ideas? Or maybe the hyperparameter in my settings is not right? 
Thanks!

**Comment by buptcwk** [comment]
We ran these two methods on the Chaoyang dataset based on their public code, and if my memory is correct, I just changed the model backbone and the dataset.
